/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'TokenA', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenA__factory>
getContractFactory(name: 'TokenB', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenB__factory>
getContractFactory(name: 'TokenSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenSwap__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'Events', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Events__factory>

  getContractAt(name: 'TokenA', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenA>
getContractAt(name: 'TokenB', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenB>
getContractAt(name: 'TokenSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenSwap>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'Events', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Events>

  deployContract(name: 'TokenA', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenA>
deployContract(name: 'TokenB', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenB>
deployContract(name: 'TokenSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenSwap>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'Events', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Events>

  deployContract(name: 'TokenA', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenA>
deployContract(name: 'TokenB', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenB>
deployContract(name: 'TokenSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenSwap>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'Events', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Events>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  